name: nbiot-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.3
  - pip
  - numpy=2.2.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - lightgbm=4.6.0
  - joblib=1.5.0
  - fastapi>=0.115.12
  - uvicorn=0.34.2
  - pydantic=2.11.4
  - pytest=8.3.5
  - pytest-cov=6.2.1
  - pytest-mock=3.14.0
  - httpx=0.28.1
  - pip:
    - python-multipart==0.0.22
    - opentelemetry-api==1.33.1
    - opentelemetry-exporter-otlp-proto-http==1.33.1
    - opentelemetry-instrumentation-fastapi==0.54b1
    - opentelemetry-instrumentation-logging==0.54b1
    - opentelemetry-sdk==1.33.1
