apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nbiot-detector

patches:
  - path: patch-deployment.yaml
  - path: patch-http-route.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
