apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbiot-detector
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nbiot-detector
        image: minhtuan172/nbiot-detector-app:main-6-9a0d4ca
        resources:
          requests:
            cpu: "30m"
            memory: "150Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"


