apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbiot-detector
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nbiot-detector
        image: minhtuan172/nbiot-detector-app:main-17-b96f325
        resources:
          requests:
            cpu: "100m"


