apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nbiot-detector-route
spec:
  hostnames:
  - "app.tuan-lnm.org"
  rules:
  - backendRefs:
    - name: nbiot-detector
      port: 8000