apiVersion: v1
kind: Service
metadata:
  name: nbiot-detector
  labels:
    app: nbiot-detector
spec:
  type: ClusterIP
  selector:
    app: nbiot-detector
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
